branches:
  only:
    - master
language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"
sudo: false
notifications:
  email:
    on_success: never
    on_failure: always
  webhooks:
    urls:
      - https://www.oriskami.com/data/webhooks/travis-ci 
    on_success: always
    on_failure: always
    on_start: always  
    on_cancel: always
    on_error: always 
