branches:
  only:
    - master
matrix:
  allow_failures:
    - os: osx
language: node_js
os:
  - linux
  - osx
node_js:
  - "v0.10"
  - "v0.11"
  - "v0.12"
  - "v1"
  - "v2"
  - "v3"
  - "v4"
  - "v5"
  - "v6"
  - "v7"
  - "v8"
  - "v9"
  - "v10"
sudo: false
notifications:
  email:
    on_success: never
    on_failure: always
  webhooks:
    urls:
      - https://www.oriskami.com/data/webhooks/travis-ci 
    on_success: always
    on_failure: always
    on_start: always  
    on_cancel: always
    on_error: always 
